### ISSUE TITLE
Change the behavior of the heatmap away from a density function

### ISSUE THREAD

**Issue by Madministrator** [wifiheatmap/wifiheatmap#14]
the heatmap should show the strength or intensity of each individual point rather than the density of all points together as clusters currently give a stronger rating then it should.

**Comment by Madministrator** [comment]
https://developers.google.com/maps/documentation/javascript/heatmaplayer

see the paragraph on max intensity

**Comment by Madministrator** [comment]
So, I've fixed the issue by switching to a max intensity function, but the behavior of the heatmap still isn't right. I think that the fundamental problem with the heatmap is that Google's idea of a heatmap is different than what our idea of a heatmap is. We need to overhaul the drawing methods to draw individual shapes using primitives that we can draw over a google map.

**Comment by Austin-Scott** [comment]
Issues #16 and #19 can be solved at the same time as this issue.
