### ISSUE TITLE
Add a setting to allow the user to change the refresh rate

### ISSUE THREAD

**Issue by Madministrator** [wifiheatmap/wifiheatmap#15]

**Comment by Madministrator** [comment]
this refresh rate seems to providing a bigger problem, the data collection itself is only occurring every ten seconds. The data collection should be continuous while the display update should be the only throttled thing. We need to get really specific about this delay behavior or else the app is not working as expected.

**Comment by Austin-Scott** [comment]
This issue is no longer valid as the heatmap now refreshes as soon as new data is available.
